apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: c3-keycloak
  namespace: keycloak
spec:
  instances: 1

  # Simple in-memory DB for learning
  db:
    vendor: dev-mem

  # Expose via simple hostname
  hostname:
    hostname: keycloak.local

  # Enable HTTP (no TLS) for dev
  http:
    httpEnabled: true
