apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: c3-keycloak
  namespace: keycloak
spec:
  instances: 1

  # Admin credentials used to log in to Keycloak UI
  bootstrapAdmin:
    username: admin
    passwordSecret: c3-keycloak-admin

  # Ephemeral internal DB (for learning)
  db:
    vendor: dev-mem

  # Configure ingress
  http:
    ingress:
      enabled: true
      className: nginx
      hostname: keycloak.local
